baseURL = 'http://example.org/'
languageCode = 'zh-cn'
title = "wzkMaster's Blogs"
theme = 'paper'

[params]
  color = "linen"
  github = "wzkMaster"
  name = "wzkMaster"
  bio = "WHU信管专业大四在读，即将入职阿里的前端开发工程师岗位。"
  avatar = "https://avatars.githubusercontent.com/u/56303938?s=400&u=16c19c4347e2cef53271c43bd458c6cce4ceac69&v=4"
